version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bidding
      POSTGRES_USER: bidding
      POSTGRES_PASSWORD: bidding
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
